<?php if ($this->pageCount): ?>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-xs-12 col-lg-4 mt-5">
            <ul class="pagination">
            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
                <li class="page-item">
                <a class="page-link" href="<?= $this->url($this->route, ["action" => $this->action], ['query' => ['page' => $this->previous]]) ?>">
                    &lt;&lt;
                </a>
                </li>
            <?php else: ?>
                <li class="page-item disabled">
                <a class="page-link" href="#">
                    &lt;&lt;
                </a>
                </li>
            <?php endif ?>

            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page !== $this->current): ?>
                <li class="page-item">
                    <a class="page-link" href="<?= $this->url($this->route, ["action" => $this->action], ['query' => ['page' => $page]]) ?>">
                    <?= $page ?>
                    </a>
                </li>
                <?php else: ?>
                <li class="page-item active">
                    <a class="page-link" href="#"><?= $page ?></a>
                </li>
                <?php endif ?>
            <?php endforeach ?>

            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
                <li class="page-item">
                <a class="page-link" href="<?= $this->url($this->route, ["action" => $this->action], ['query' => ['page' => $this->next]]) ?>">
                    &gt;&gt;
                </a>
                </li>
            <?php else: ?>
                <li class="page-item disabled">
                <a class="page-link" href="#">
                    &gt;&gt;
                </a>
                </li>
            <?php endif ?>
            </ul>
        </div>
    </div>
</div>
<?php endif ?>