<?php

$title = 'Catalogue';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<div class='media my-3 jumbotron row'>
	<img src='http://placeholder.pics/svg/300' class='rounded col-md-4 col-sm-12'/>
	<div class='media-body mx-3 col-md-8 col-sm-12'>
		<h3><a href="<?= $this->url('produit', ["action" => "description", "id" => $produit->id]) ?>"><?= $produit->nom ?></a></h3>
		<p><?= $produit->description ?></p>
		<p>Prix: <?= number_format($produit->prix,2,'.',' ') ?> $</p>
		<a href="<?= $this->url('produit', ['action' => 'ajouterPanier', 'id' => $produit->id]) ?>" role="button" class='btn btn-primary'>Ajouter au panier</a>
	</div>
</div>
