<?php
$title = 'Modifier un produit';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$nom = $form->get('nom');
$nom->setAttribute('class', 'form-control');
$nom->setAttribute('placeholder', 'Nom');

$description = $form->get('description');
$description->setAttribute('class', 'form-control');
$description->setAttribute('placeholder', 'Description');


$prix = $form->get('prix');
$prix->setAttribute('class', 'form-control');
$prix->setAttribute('placeholder', 'Prix');


// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('produit', ['action' => 'edit', 'id' => $id]));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within ?>
<div class="form-group">
    <?= $this->formLabel($nom) ?>
    <?= $this->formElement($nom) ?>
    <?= $this->formElementErrors()->render($nom, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($description) ?>
    <?= $this->formElement($description) ?>
    <?= $this->formElementErrors()->render($description, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($prix) ?>
    <?= $this->formElement($prix) ?>
    <?= $this->formElementErrors()->render($prix, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();