<?php

$title = 'Panier';
$this->headTitle($title);
?>

<h1><?= $this->escapeHtml($title) ?></h1>

<?php if (!empty($produits)) : ?>
<?php $sousTotal = 0; ?>
  <div class="row">
    <div class="col-md-8 col-sm-12 border justify-content-center rounded-top m-1 p-0">
        <table class="table table-sm text-left m-0">
            <thead class="thead-light">
                <tr>
                    <th class="p-2 border-0">Image</th>
                    <th class="p-2 border-0">Nom</th>
                    <th class="p-2 border-0">Description</th>
                    <th class="p-2 border-0 text-right">Prix</th>
                    <th class="border-0"></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($produits as $produit) : ?>
                <tr>
                    <td class="text-left"><img src='http://placeholder.pics/svg/100'/></td>
                    <td class="text-left align-middle"><a href="<?= $this->url('produit', ["action" => "description", "id" => $produit->id]) ?>"><?= $produit->nom ?></a></td>
                    <td class="text-left align-middle"><?= $produit->description ?></td>
                    <td class="text-right align-middle"><?= number_format($produit->prix,2,'.',' ') ?> $</td>
                    <td class="text-center align-middle">
                    <a href="<?= $this->url('produit' , ['action' => 'retirerPanier', 'id' => $produit->id]) ?>" role="button" class='btn btn-danger'/>X</a>
                    </td>
                </tr>
                <?php $sousTotal += $produit->prix; ?>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php
    $tps = $sousTotal * 0.05;
    $tvq = $sousTotal * 0.09975;
    $total = $sousTotal + $tps + $tvq;
    ?>
    <div class="col border justify-content-center rounded-top p-0 m-1">
      <table class="table">
        <tbody>
          <tr>
            <td class="border-0">Sous-total: </td>
            <td class="text-right border-0"><?=number_format($sousTotal,2,'.',' ')?> $</td>
          </tr>
          <tr>
            <td>TPS: </td>
            <td class="text-right"><?=number_format($tps,2,'.',' ')?> $</td>
          </tr>
          <tr>
            <td>TVQ: </td>
            <td class="text-right"><?=number_format($tvq,2,'.',' ')?> $</td>
          </tr>
          <tr>
            <td>Total: </td>
            <td class="text-right"><?=number_format($total,2,'.',' ')?> $</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <a href="<?= $this->url('produit', ['action' => 'viderPanier']) ?>" role="button" class='btn btn-danger'/>Vider Panier</a>
  <a href="<?= $this->url('produit', ['action' => 'payer']) ?>" role="button" class='btn btn-success float-right'/>Payer</a>

<?php else : ?>

    <div class="jumbotron">
    <h1 class="display-3">Votre panier est vide :(</h1>
    <hr class="my-4">
    <p>Vous feriez mieux de revenir au catalogue</p>
    <a class="btn btn-primary btn-lg" href="<?= $this->url('produit')?>" role="button">Retour au catalogue</a>
    </div>
    
<?php endif;