<?php
$this->headTitle('Connexion');

$form->get('username')->setAttributes([
    'class'=>'form-control my-3', 
    'placeholder'=>"Nom d'utilisateur",
    'required' => true,
    'autofocus' => true
    ])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);

$form->get('password')->setAttributes([
    'class'=>'form-control my-3', 
    'placeholder'=>'Mot de passe',
    'required' => true,
    ])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);
$form->get('submit')->setAttributes([
    'class'=>'btn btn-lg btn-primary btn-block my-3', 
    'placeholder'=>'Mot de passe'
    ]);
?>

<div class="row justify-content-center">
    <div class="col-md-offset-4 col-md-3">
        <form class="form-signin" method="post">
            <h2 class="form-signin-heading">Connexion</h2>
            <?php if ($isLoginError): ?>
            <div class="alert alert-warning" role="alert">
                Nom d'utilisateur ou mot de passe invalide. 
            </div>
            <?php endif; ?>
            <?= $this->formLabel($form->get('username')); ?>
            <?= $this->formElement($form->get('username')); ?>
            <?= $this->formLabel($form->get('password')); ?>
            <?= $this->formElement($form->get('password')); ?>
            <?= $this->formElement($form->get('redirect_url')); ?>
            <?= $this->formElement($form->get('csrf')) ?>
            <?= $this->formElement($form->get('submit')) ?>
        </form>
    </div>
</div>